name: Deploy TypeScript Frontend

env:
  SSH_PORT: 2026

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  frontend-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install  dependencies 
      - name: Install  dependencies
        run: npm ci
      
      # Run unit + integration tests
      - name: Run tests
        run: |
          npm run test:ci
          npm run test:coverage
      
      # Build frontend
      - name: Build frontend
        run: npm run build

      # Start SSH agent with GitHub secret key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Add server to known_hosts 
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $SSH_PORT barryonweb.com >> ~/.ssh/known_hosts
      
      # Nginx config - transfer, enable, check syntax and restart Nginx
      - name: Update Nginx config
        run: |
          scp -P $SSH_PORT webshop-dev.barryonweb.com barry75@barryonweb.com:/var/www/webshop/
          ssh -p $SSH_PORT barry75@barryonweb.com "
            sudo cp /var/www/webshop/webshop-dev.barryonweb.com /etc/nginx/sites-available/ &&
            sudo ln -sf /etc/nginx/sites-available/webshop-dev.barryonweb.com /etc/nginx/sites-enabled/ &&
            sudo nginx -t &&
            sudo systemctl reload nginx"
      
      # Transfer frontend from GitHub Repo to Ubuntu server via SCP
      - name: Deploy frontend via SCP
        run: |
          scp -r -P $SSH_PORT dist/* barry75@barryonweb.com:/var/www/webshop/frontend/
